<a href="https://colab.research.google.com/github/Kausharalam7/Generative-AI/blob/main/Simple_RNN_projects.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your vidoes are good'
]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your vidoes are good']

In [ ]:
# defin the vocabulary sizze
voc_size=10000

In [ ]:
# one hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[5594, 59, 5547, 5461],
 [5594, 59, 5547, 5437],
 [5594, 3105, 5547, 9403],
 [1088, 51, 5011, 2976, 449],
 [1088, 51, 5011, 2976, 4467],
 [4942, 5594, 9935, 5547, 8297],
 [5076, 5342, 9809, 2976]]

In [ ]:
# word embedding representaation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [ ]:
import numpy as np

In [ ]:
sent_length=10
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0    0    0 5594   59 5547 5461]
 [   0    0    0    0    0    0 5594   59 5547 5437]
 [   0    0    0    0    0    0 5594 3105 5547 9403]
 [   0    0    0    0    0 1088   51 5011 2976  449]
 [   0    0    0    0    0 1088   51 5011 2976 4467]
 [   0    0    0    0    0 4942 5594 9935 5547 8297]
 [   0    0    0    0    0    0 5076 5342 9809 2976]]


In [ ]:
#feature representation
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_shape=(sent_length,)))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)              │ (None, 10, 10)              │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step


array([[[ 2.6390482e-02,  3.2133460e-03,  2.9503588e-02,  3.1657342e-02,
          3.8457561e-02,  2.0808708e-02,  4.4106688e-02, -1.9173598e-02,
         -3.7353646e-02,  3.9684858e-02],
        [ 2.6390482e-02,  3.2133460e-03,  2.9503588e-02,  3.1657342e-02,
          3.8457561e-02,  2.0808708e-02,  4.4106688e-02, -1.9173598e-02,
         -3.7353646e-02,  3.9684858e-02],
        [ 2.6390482e-02,  3.2133460e-03,  2.9503588e-02,  3.1657342e-02,
          3.8457561e-02,  2.0808708e-02,  4.4106688e-02, -1.9173598e-02,
         -3.7353646e-02,  3.9684858e-02],
        [ 2.6390482e-02,  3.2133460e-03,  2.9503588e-02,  3.1657342e-02,
          3.8457561e-02,  2.0808708e-02,  4.4106688e-02, -1.9173598e-02,
         -3.7353646e-02,  3.9684858e-02],
        [ 2.6390482e-02,  3.2133460e-03,  2.9503588e-02,  3.1657342e-02,
          3.8457561e-02,  2.0808708e-02,  4.4106688e-02, -1.9173598e-02,
         -3.7353646e-02,  3.9684858e-02],
        [ 2.6390482e-02,  3.2133460e-03,  2.9503588e-02,  3.

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0, 5594,   59, 5547, 5461],
      dtype=int32)

**End to end deep learning projects using Simple RNN**

In [48]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense

In [49]:
# load the dataset
max_features=10000  ## vocobulary size
(X_train,y_train),(X_test,y_test)=imdb.load_data(num_words=max_features)

# print the shape of the data
print(f"Training data shape: {X_train.shape}, Training labels shape: {y_train.shape}")
print(f"Testing data shape: {X_train.shape}, Testing labels shape: {y_test.shape}")

Training data shape: (25000,), Training labels shape: (25000,)
Testing data shape: (25000,), Testing labels shape: (25000,)


In [50]:
X_train[0],y_train[0]

([1,
  14,
  22,
  16,
  43,
  530,
  973,
  1622,
  1385,
  65,
  458,
  4468,
  66,
  3941,
  4,
  173,
  36,
  256,
  5,
  25,
  100,
  43,
  838,
  112,
  50,
  670,
  2,
  9,
  35,
  480,
  284,
  5,
  150,
  4,
  172,
  112,
  167,
  2,
  336,
  385,
  39,
  4,
  172,
  4536,
  1111,
  17,
  546,
  38,
  13,
  447,
  4,
  192,
  50,
  16,
  6,
  147,
  2025,
  19,
  14,
  22,
  4,
  1920,
  4613,
  469,
  4,
  22,
  71,
  87,
  12,
  16,
  43,
  530,
  38,
  76,
  15,
  13,
  1247,
  4,
  22,
  17,
  515,
  17,
  12,
  16,
  626,
  18,
  2,
  5,
  62,
  386,
  12,
  8,
  316,
  8,
  106,
  5,
  4,
  2223,
  5244,
  16,
  480,
  66,
  3785,
  33,
  4,
  130,
  12,
  16,
  38,
  619,
  5,
  25,
  124,
  51,
  36,
  135,
  48,
  25,
  1415,
  33,
  6,
  22,
  12,
  215,
  28,
  77,
  52,
  5,
  14,
  407,
  16,
  82,
  2,
  8,
  4,
  107,
  117,
  5952,
  15,
  256,
  4,
  2,
  7,
  3766,
  5,
  723,
  36,
  71,
  43,
  530,
  476,
  26,
  400,
  317,
  46,
  7,
  4,
  2,
  1029,
  

In [51]:
# Inspect a sample review and its label
sample_review=X_train[0]
sample_label=y_train[0]

print(f"sample review (as integers): {sample_review}")
print(f"sample label: {sample_label}")

sample review (as integers): [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]
sample label: 1


In [52]:
#mapping of words index back to words (for understanding)
word_index=imdb.get_word_index()
# word_index
reverse_word_index={value: key for key, value in word_index.items()}
reverse_word_index


{34701: 'fawn',
 52006: 'tsukino',
 52007: 'nunnery',
 16816: 'sonja',
 63951: 'vani',
 1408: 'woods',
 16115: 'spiders',
 2345: 'hanging',
 2289: 'woody',
 52008: 'trawling',
 52009: "hold's",
 11307: 'comically',
 40830: 'localized',
 30568: 'disobeying',
 52010: "'royale",
 40831: "harpo's",
 52011: 'canet',
 19313: 'aileen',
 52012: 'acurately',
 52013: "diplomat's",
 25242: 'rickman',
 6746: 'arranged',
 52014: 'rumbustious',
 52015: 'familiarness',
 52016: "spider'",
 68804: 'hahahah',
 52017: "wood'",
 40833: 'transvestism',
 34702: "hangin'",
 2338: 'bringing',
 40834: 'seamier',
 34703: 'wooded',
 52018: 'bravora',
 16817: 'grueling',
 1636: 'wooden',
 16818: 'wednesday',
 52019: "'prix",
 34704: 'altagracia',
 52020: 'circuitry',
 11585: 'crotch',
 57766: 'busybody',
 52021: "tart'n'tangy",
 14129: 'burgade',
 52023: 'thrace',
 11038: "tom's",
 52025: 'snuggles',
 29114: 'francesco',
 52027: 'complainers',
 52125: 'templarios',
 40835: '272',
 52028: '273',
 52130: 'zaniacs',

In [53]:
decoded_review = ' '.join([reverse_word_index.get(i-3,'?') for i in sample_review])
decoded_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [54]:
from tensorflow.keras.preprocessing import sequence
max_len=500
X_train=sequence.pad_sequences(X_train,maxlen=max_len)
X_test=sequence.pad_sequences(X_test,maxlen=max_len)
X_train

array([[   0,    0,    0, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [55]:
X_train[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [60]:
# train simple rnn
model=Sequential()
model.add(Embedding(max_features, 128, input_shape=(max_len,))) # embedding layers
model.add(SimpleRNN(128,activation='relu'))
model.add(Dense(1,activation="sigmoid"))

In [61]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_10 (Embedding)             │ (None, 500, 128)            │       1,280,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_2 (SimpleRNN)             │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,313,025 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

In [65]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [66]:
# create an instance of EarlyStopping callback
from tensorflow.keras.callbacks import EarlyStopping
earlystopping=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)
earlystopping

In [68]:
# train the model with earlystopping
history=model.fit(
    X_train,y_train,epochs=10,batch_size=32,
    validation_split=0.2,
    callbacks=[earlystopping]
)

Epoch 1/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 135s 212ms/step - accuracy: 0.5829 - loss: 56.0247 - val_accuracy: 0.6452 - val_loss: 0.6170
Epoch 2/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 143s 213ms/step - accuracy: 0.7017 - loss: 20.0338 - val_accuracy: 0.6842 - val_loss: 0.5801
Epoch 3/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 127s 203ms/step - accuracy: 0.7771 - loss: 0.4997 - val_accuracy: 0.7118 - val_loss: 0.5545
Epoch 4/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 145s 208ms/step - accuracy: 0.8255 - loss: 0.4278 - val_accuracy: 0.7274 - val_loss: 0.5400
Epoch 5/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 143s 210ms/step - accuracy: 0.8595 - loss: 0.3687 - val_accuracy: 0.7366 - val_loss: 0.5348
Epoch 6/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 130s 208ms/step - accuracy: 0.8922 - loss: 0.3066 - val_accuracy: 0.7470 - val_loss: 0.5445
Epoch 7/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 139s 203ms/step - accuracy: 0.9099 - loss: 0.2564 - val_accuracy: 0.7512 - val_loss: 0.5580
Epoch 8/10
625/625 ━━━━━━━━━━━━━━━━━━━━ 131s 209ms/step - accuracy: 0.8835

In [70]:
# save the model
model.save('simple_rnn_imdb.h5')

Prediction

In [71]:
# Step 1: Import Libraries and Load the Model
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.models import load_model

In [72]:
# Load the IMDB dataset word index
word_index = imdb.get_word_index()
reverse_word_index = {value: key for key, value in word_index.items()}

In [73]:
# Load the pre-trained model with ReLU activation
model = load_model('simple_rnn_imdb.h5')
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_10 (Embedding)             │ (None, 500, 128)            │       1,280,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_2 (SimpleRNN)             │ (None, 128)                 │          32,896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,313,027 (5.01 MB)

 Trainable params: 1,313,025 (5.01 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [74]:
model.get_weights()

[array([[-7.2551835e-01,  7.3055059e-01,  7.1560913e-01, ...,
         -7.1397215e-01, -7.4922448e-01, -7.4266022e-01],
        [ 2.0781210e-02,  6.8224266e-02,  1.3841986e-02, ...,
         -1.4646105e-02, -1.4120278e-02, -6.8627350e-02],
        [-3.1829581e-02,  4.7290912e-03,  1.2906410e-01, ...,
         -1.3068835e-01, -8.7566100e-02, -7.6906137e-02],
        ...,
        [-3.2173436e-02, -1.2034130e-01, -1.2158910e-01, ...,
         -1.7135790e-02,  5.8020079e-05, -1.0606493e-01],
        [ 3.3539683e-02, -3.4820717e-02, -7.1488976e-02, ...,
         -2.2620568e-02,  5.0515801e-02, -1.4788966e-02],
        [-4.2863503e-02,  1.7784135e-02, -3.8566675e-02, ...,
         -1.2102430e-01, -9.8602884e-02, -5.6274228e-02]], dtype=float32),
 array([[-0.05976534, -0.16288957, -0.2120059 , ...,  0.05910718,
          0.15615112, -0.09784191],
        [-0.02539278,  0.08904713,  0.14912559, ...,  0.13302399,
         -0.00516977,  0.0128854 ],
        [-0.04538144, -0.05631411,  0.09199043

In [75]:
#  Step 2: Helper Functions
# Function to decode reviews
def decode_review(encoded_review):
    return ' '.join([reverse_word_index.get(i - 3, '?') for i in encoded_review])

# Function to preprocess user input
def preprocess_text(text):
    words = text.lower().split()
    encoded_review = [word_index.get(word, 2) + 3 for word in words]
    padded_review = sequence.pad_sequences([encoded_review], maxlen=500)
    return padded_review

In [76]:
### Prediction  function

def predict_sentiment(review):
    preprocessed_input=preprocess_text(review)

    prediction=model.predict(preprocessed_input)

    sentiment = 'Positive' if prediction[0][0] > 0.5 else 'Negative'

    return sentiment, prediction[0][0]

In [77]:
# Step 4: User Input and Prediction
# Example review for prediction
example_review = "This movie was fantastic! The acting was great and the plot was thrilling."

sentiment,score=predict_sentiment(example_review)

print(f'Review: {example_review}')
print(f'Sentiment: {sentiment}')
print(f'Prediction Score: {score}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 197ms/step
Review: This movie was fantastic! The acting was great and the plot was thrilling.
Sentiment: Positive
Prediction Score: 0.999996542930603
